Basic refactoring of code
adityaa30/cp-cli pull request #6
Opened 2020-09-17 18:31 UTC by avikumar15

Distributed cli.py into smaller python class files.

2020-09-17 22:20 UTC, adityaa30 commented
Looks really good. Some of suggestions I have:
Instead of the current file tree how about we change it to:
```text
src/cpcli
|-- __init__.py
|-- cmdline.py
|-- question.py
|-- scrapper.py
|-- testcase.py
|-- commands
|   |-- __init__.py
|   |-- download.py
|   |-- init.py
|   |-- run.py
|   |-- show.py
|   `-- testcase.py
|-- platforms
|   |-- __init__.py
|   |-- codechef.py
|   `-- codeforces.py
`-- utils
    |-- __init__.py
    |-- cmdtypes.py
    |-- config.py
    |-- constants.py
    |-- exceptions.py
    |-- misc.py
    `-- python.py
```

2020-09-18 14:49 UTC, adityaa30 reviewed
Looks good. How about we change `Scrapper` to `Runner` ?

2020-09-18 14:49 UTC, narutosasuke30 commented on src/cpcli/question.py
> +WHITE_SPACES = string.whitespace
Move `WHITE_SPACES` to `utils/constants.py`. (Same for `testcase.py`)

2020-09-18 14:56 UTC, avikumar15 commented on src/cpcli/question.py
> +WHITE_SPACES = string.whitespace
Sure!

2020-09-19 23:57 UTC, adityaa30 requested changes

2020-09-19 23:57 UTC, adityaa30 commented on src/cpcli/commands/testcase.py
> +    def run(self, args: Namespace, scraper: Runner) -> None:
```suggestion
    def run(self, args: Namespace, runner: Runner) -> None:
```

This should be renamed as well? (same for all the other occurences)

2020-09-20 23:45 UTC, adityaa30 approved these changes

2020-09-20 23:46 UTC, merged